project_id = "wearwell"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
major_version = 17

[auth]
enabled = true
site_url = "wearwell://auth-callback"
additional_redirect_urls = ["wearwell://auth-callback"]

[storage]
enabled = true
file_size_limit = "18MiB"
